### ISSUE TITLE
Hardware modifications pending

### ISSUE THREAD

**Issue by tiffanyona** [AllenNeuralDynamics/aind-vr-foraging#22]
Things that need to be upgraded or updated in the rigs:

**Room**
- [x] Paint chips - Update, they will be painted over the weekend
- [x] Place air hose
- [x] Put tables (at least keyboard there. 
- [x] Install waterlog

**Box VR 4.** 
- [x] Add pressure sensor tubing. 
- [x] Place the odor vials. 
- [x] Add odor tubing. 
- [x] Change speaker position. 
- [ ] Calibrate water valve
- [x] Place new stage. Ensure everything still works. Report back to Nathan. 
- [x] Connect the servo.  
- [ ] Place thermistor board

**Box VR 2**
- [x] Adjust height. 
- [x] Add pressure sensor tubing. 
- [x] Add lenses.
- [x] Connect camera cables. 
- [x] Change lenses for 8mm. 
- [x] Change speaker position. 
- [x] Add odor tubing. 
- [x] Calibrate water valve
- [ ] Place thermistor board
- [x] Solder extra ground.
